// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4vb-Bw_KYnYYOhynswcZKF25RRu6Do1s',
    appId: '1:906335682070:web:764ec50b5f71a207d67f37',
    messagingSenderId: '906335682070',
    projectId: 'applicationwasalny',
    authDomain: 'applicationwasalny.firebaseapp.com',
    storageBucket: 'applicationwasalny.firebasestorage.app',
    measurementId: 'G-W938PWGLJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTkVGLjBvhVQi2DoC3V8BgD1GPjSmixw',
    appId: '1:906335682070:android:0386aba53a04c190d67f37',
    messagingSenderId: '906335682070',
    projectId: 'applicationwasalny',
    storageBucket: 'applicationwasalny.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpmTpY5gqqMaXqjXbtSwG18OzfD6I5diA',
    appId: '1:906335682070:ios:b7e20b3ae2a7ebf4d67f37',
    messagingSenderId: '906335682070',
    projectId: 'applicationwasalny',
    storageBucket: 'applicationwasalny.firebasestorage.app',
    iosBundleId: 'com.example.wasalny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpmTpY5gqqMaXqjXbtSwG18OzfD6I5diA',
    appId: '1:906335682070:ios:b7e20b3ae2a7ebf4d67f37',
    messagingSenderId: '906335682070',
    projectId: 'applicationwasalny',
    storageBucket: 'applicationwasalny.firebasestorage.app',
    iosBundleId: 'com.example.wasalny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4vb-Bw_KYnYYOhynswcZKF25RRu6Do1s',
    appId: '1:906335682070:web:471696d905366bbbd67f37',
    messagingSenderId: '906335682070',
    projectId: 'applicationwasalny',
    authDomain: 'applicationwasalny.firebaseapp.com',
    storageBucket: 'applicationwasalny.firebasestorage.app',
    measurementId: 'G-MKS4ZE15CZ',
  );

}